services:
  db:
    image: mysql:8.0
    container_name: concesionario_rmz
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: concesionario_rmz
    ports:
      - "3306:3306"
    networks:
      app_network:
        ipv4_address: 172.18.0.2 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  app:
    image: pansete/gescon_rmz:latest
    container_name: gescon_rmz  
    ports:
      - "3000:3000"
    networks:
      app_network:
        ipv4_address: 172.18.0.3
    depends_on:
      - db
    environment:
      - DB_PASS=root

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  db_data: